### ISSUE TITLE
01_MIP存储.md 中部分代码无法通过fecs校验

### ISSUE THREAD

**Issue by Roscoe93** [mipengine/mip-blog#7]
```js
var customStorage = new util.customStorage([type]);
```
这段在fecs校验时会提示 A constructor name should not start with a lowercase letter.

**Comment by wupengFEX** [comment]
@Roscoe93 这一块我们会统一review一下，看下修改方案，感谢！

**Comment by wupengFEX** [comment]
可以通过下面这种方式进行使用
var CustomStorage = util.customStorage;
new CustomStorage([type]);
